"""
LLM client module for the LLM Router.

This module handles communication between the router and the Google Gemini
models.

Its main responsibilities are:
    - Creating the Gemini API client.
    - Looking up model information from config.py.
    - Sending prompts to either the cheap or strong LLM.
    - Asking the cheap model for a confidence score when requested.
    - Extracting the confidence score from the model's response.
    - Tracking input and output token usage.
    - Calculating the estimated cost of each LLM call.
    - Measuring how long each LLM call takes.
    - Retrying requests when temporary API rate/quota limits occur.
    - Returning all information about an LLM call as an LLMResult.
"""

import os
import time
import re
import logging
from dataclasses import dataclass

from google import genai
from google.genai import types
from google.genai import errors as genai_errors

from . import config

logging.getLogger("google_genai.models").setLevel(logging.ERROR)

# GEMINI CLIENT
# Creates the client used to communicate with Google's Gemini API.
# The API key is read from the GOOGLE_API_KEY environment variable instead
# of being written directly into the source code.
_client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))


@dataclass
class LLMResult:
    """
    Stores the result and metadata from one LLM API call.

    Attributes:
        text: The text response generated by the LLM.

        model_key: The role of the model in the router.
            This will normally be "cheap" or "strong".

        model_name: The actual Gemini model name defined in config.py.

        input_tokens: Number of tokens sent to the LLM.

        output_tokens: Number of tokens generated by the LLM.

        cost_usd: Estimated cost of the API call in U.S. dollars.

        latency_s: Number of seconds the API call took.

        confidence: Confidence score reported by the LLM when
            ask_confidence=True. Otherwise, this is None.
    """
    text: str
    model_key: str        # "cheap" or "strong"
    model_name: str
    input_tokens: int
    output_tokens: int
    cost_usd: float
    latency_s: float
    confidence: float | None = None  # only populated for cheap-model calls


def _cost(model_key: str, input_tokens: int, output_tokens: int) -> float:
    """
    Calculate the estimated cost of one LLM call.
    The price of each model is stored in config.py as the cost per
    one million input and output tokens.

    Args:
        model_key: The model role, such as "cheap" or "strong".
        input_tokens: Number of tokens sent to the model.
        output_tokens: Number of tokens generated by the model.

    Returns:
        The estimated total cost of the LLM call in U.S. dollars.
    """

    # Get the selected model's pricing information from config.py.
    m = config.MODELS[model_key]
    return (
        input_tokens / 1_000_000 * m["price_in_per_m"]
        + output_tokens / 1_000_000 * m["price_out_per_m"]
    )

# Finds a confidence score written by the LLM
_CONFIDENCE_RE = re.compile(r"CONFIDENCE:\s*([0-9.]+)", re.IGNORECASE)

# Looks for a retry delay inside a Google API error message.
# For example:
#     "retry in 12.5s"
#
# This allows the program to determine how long it should wait before
# attempting the API call again.
_RETRY_DELAY_RE = re.compile(r"retry in ([0-9.]+)s", re.IGNORECASE)


def _call_with_quota_retry(model_name: str, prompt: str, max_retries: int = 2):
    """
    Send a prompt to a Gemini model and retry temporary quota failures.

    If Google returns a RESOURCE_EXHAUSTED error, the function attempts
    to determine how long Google recommends waiting. It then pauses and
    retries the request.

    Args:
        model_name: The actual Gemini model name to call.
        prompt: The text that will be sent to the model.
        max_retries: Maximum number of retries after the first attempt.

    Returns:
        The response returned by the Gemini API.

    Raises:
        ClientError: If the error is not a temporary quota error or all
            retry attempts have been used.
    """
    for attempt in range(max_retries + 1):
        try:
            return _client.models.generate_content(
                model=model_name,
                contents=prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=config.MAX_TOKENS,
                ),
            )
        except genai_errors.ClientError as e:
            is_last = attempt == max_retries
            if "RESOURCE_EXHAUSTED" not in str(e) or is_last:
                raise
            match = _RETRY_DELAY_RE.search(str(e))
            wait_s = float(match.group(1)) + 1.0 if match else 30.0
            print(f"    (rate/quota limit hit on {model_name}, "
                  f"waiting {wait_s:.0f}s before retry {attempt + 1}/{max_retries}...)")
            time.sleep(wait_s)


def call_model(model_key: str, query: str, ask_confidence: bool = False,) -> LLMResult:
    """
    Call either the cheap or strong LLM.

    If ask_confidence=True, the prompt is modified so that the LLM is
    explicitly asked to report a confidence score between 0 and 1.

    The function then:
        1. Builds the prompt.
        2. Calls the selected Gemini model.
        3. Measures the API call's latency.
        4. Extracts the generated text.
        5. Extracts the confidence score if one was requested.
        6. Gets input and output token counts.
        7. Calculates the estimated cost.
        8. Returns everything as an LLMResult.

    Args:
        model_key: Which model to use, such as "cheap" or "strong".
        query: The original user query.
        ask_confidence: Whether the LLM should also generate a confidence
            score for its answer.

    Returns:
        An LLMResult containing the response and information about the call.
    """

    # Get the selected model's configuration from config.py.
    model_cfg = config.MODELS[model_key]

    prompt = (
        "Answer the user's question completely but concisely. "
        "Prioritize the important information and avoid unnecessary detail.\n\n"
        f"Question: {query}"
    )

    if ask_confidence:
        prompt = (
            "Answer the user's question directly and concisely. "
            "After your answer, on a new line, output exactly: "
            "CONFIDENCE: <a number between 0 and 1 indicating how confident "
            "you are that your answer is correct and complete>.\n\n"
            f"Question: {query}"
        )

    start = time.perf_counter()

    # Send the prompt to the selected Gemini model.
    resp = _call_with_quota_retry(model_cfg["name"], prompt)

    latency = time.perf_counter() - start

    text = resp.text or ""

    confidence = None

    if ask_confidence:
        # Search the model's response for the confidence score.
        match = _CONFIDENCE_RE.search(text)

        if match:
            confidence = float(match.group(1))

            # Remove the CONFIDENCE line so the user only sees the answer.
            text = _CONFIDENCE_RE.sub("", text).strip()

    # Gemini returns information about how many tokens were used.
    usage = resp.usage_metadata

    input_tokens = usage.prompt_token_count if usage else 0
    output_tokens = usage.candidates_token_count if usage else 0

    return LLMResult(
        text=text,
        model_key=model_key,
        model_name=model_cfg["name"],
        input_tokens=input_tokens or 0,
        output_tokens=output_tokens or 0,
        cost_usd=_cost(model_key, input_tokens or 0, output_tokens or 0),
        latency_s=latency,
        confidence=confidence,
    )
