"""
Configuration settings for the LLM Router.

This module stores the models, pricing information, and thresholds used
throughout the routing system.

The main settings control:
    - Which LLM is considered the cheap model.
    - Which LLM is considered the strong model.
    - Which LLM is used to judge answer quality during evaluation.
    - When a query should be routed to the strong model.
    - When a cheap-model response should be escalated.
    - How similar two queries must be for a semantic cache hit.
    - The maximum number of tokens generated by an LLM.

Other modules import these values instead of hard-coding them, making
the router's behavior easier to configure.
"""

# MODEL CONFIGURATION
# Defines the LLMs used by the system and their estimated prices.
# There are three model roles:
#
#     cheap  -> Handles queries that appear relatively simple.
#
#     strong -> Handles more complex queries and queries escalated
#               because the cheap model had low confidence.
#
#     judge  -> Used by the evaluation system to score the quality
#               of generated responses.
#
# price_in_per_m:
#     Cost in USD for one million input tokens.
#
# price_out_per_m:
#     Cost in USD for one million output tokens.
# These prices allow the system to estimate how much each LLM call costs.
MODELS = {
    "cheap": {
        "name": "gemini-3.5-flash-lite",
        "price_in_per_m": 0.30,
        "price_out_per_m": 2.50,
    },
    "strong": {
        "name": "gemini-3.5-flash",
        "price_in_per_m": 1.50,
        "price_out_per_m": 9.00,
    },
    "judge": {
        "name": "gemini-3.1-flash-lite",
        "price_in_per_m": 0.25,
        "price_out_per_m": 1.50,
    },
}

# Complexity Routing Threshold(0.0 - 1.0)
# Determines whether a query initially goes to the cheap or strong model.
COMPLEXITY_ROUTE_THRESHOLD = 0.55

# CONFIDENCE ESCALATION THRESHOLD
# This check only matters when the cheap model was initially selected.
CONFIDENCE_ESCALATION_THRESHOLD = 0.6

# SEMANTIC CACHE SIMILARITY THRESHOLD
# Determines how similar a new query must be to a previously stored query
# for the semantic cache to consider it a match.(hit)
CACHE_SIMILARITY_THRESHOLD = 0.90

# MAXIMUM OUTPUT TOKENS
# Limits how many tokens the LLM is allowed to generate in its response.
#
# A token is a small unit of text used by an LLM. A word may consist of
# one or more tokens.
#
# Limiting output tokens helps control:
#     - Response length
#     - API cost
#     - Generation time
MAX_TOKENS = 2048
